//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment_11_solution.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDo
    {
        public int ToDoId { get; set; }
        public string Description { get; set; }
        public bool IsComplete { get; set; }
    }
}
